---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twtechapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twtech
      tier: frontend
  template:
    metadata:
      labels:
        app: twtech
        tier: frontend
    spec:
      containers:
        - name: twtech
          image: learnitguide/knotejs:1.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev

---
apiVersion: v1
kind: Service
metadata:
  name: twtechappsvc
spec:
  selector:
    app: twtech
    tier: frontend

  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort
